# GitLab CI YML file dedicated for LC environment (Quartz)
#
# Spack must be available
# It would be better to install all Boost versions manually,
# as it causes errors often and could exceed the timelimit of the system.
#
# One might want to change the location of builds directory on LC clusters to avoid consuming the home directory space.
# Type the following command on an LC cluster:
# $ ln -s /usr/workspace/lc-username ~/.gitlab-runner

stages:
  - install
  - build


variables:
  GTEST_COLOR: "1"
  GIT_DEPTH: 0


install_boost:
  stage: install
  tags:
    - quartz
    - shell
  script:
    - hostname
    - srun -N1 -ppdebug spack install boost@1.82.0
    - spack clean


.build:
  stage: build
  tags:
    - quartz
    - shell
  script:
    - echo "=== build section ==="
    - module load gcc/${GCC_VERSION}
    - spack load --first boost@${BOOST_VERSION} arch=$(spack arch)
    - mkdir build && cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DBUILD_TEST=on -DBUILD_PERSISTENT_ALLOCATOR_TEST=ON -DBUILD_BOOST_CLOSED_AND_OPEN_ADDRESS_MAP_TEST=OFF -DSEPARATE_HEADER=OFF
    - make -j
    - make test
    - ./tests/random_insert_and_erase $((2**22)) 0.8 32
    - rm -f CMakeCache.txt
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DBUILD_TEST=on -DBUILD_PERSISTENT_ALLOCATOR_TEST=ON -DBUILD_BOOST_CLOSED_AND_OPEN_ADDRESS_MAP_TEST=OFF -DSEPARATE_HEADER=ON
    - make -j
    - make test
    - ./tests/random_insert_and_erase $((2**22)) 0.8 32

build_gcc12.1.1_bst1.82.0:
  extends: .build
  variables:
    GCC_VERSION: "12.1.1-magic"
    BOOST_VERSION: "1.82.0"